# Direct handles to Apicurio, requires docker compose up to work.

# List all available subjects.

GET http://localhost:9091/apis/ccompat/v6/subjects

###
# List all versions under a specific subject.

GET http://localhost:9091/apis/ccompat/v6/subjects/666/versions

###
# Add a new schema under the specified subject.

POST http://localhost:9091/apis/ccompat/v6/subjects/666/versions
Content-Type: application/json

{
  "schema": "{ \"type\": \"record\", \"name\": \"test\", \"fields\": [ { \"type\": \"string\", \"name\": \"field\" }, { \"type\": \"int\", \"name\": \"field2\" } ] }"
}

###
# List all available subjects.

GET http://localhost:8080/avroGenerator/v1/getSubjects

###
# List all versions under a specific subject.

GET http://localhost:8080/avroGenerator/v1/getSchemaVersions?subject=666

###
# Add a new schema under the specified subject.

POST http://localhost:8080/avroGenerator/v1/createSchema
Content-Type: application/json

{
  "subjectName": "666",
  "schema": "{ \"type\": \"record\", \"name\": \"test\", \"fields\": [ { \"type\": \"string\", \"name\": \"field2\" }, { \"type\": \"int\", \"name\": \"field3\" } ] }"
}

###
# Delete all schemas under the specified subject.

DELETE http://localhost:8080/avroGenerator/v1/deleteSubject
Content-Type: application/json

{
  "subjectName": "666"
}
